# Generated by Django 4.2 on 2023-05-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('cita_fecha', models.DateField()),
                ('horainicio', models.TimeField()),
                ('horafin', models.TimeField()),
                ('observacion_cita', models.CharField(blank=True, max_length=250, null=True)),
                ('estadocita', models.BooleanField()),
            ],
            options={
                'db_table': 'cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=300)),
                ('obervacion_consulta', models.CharField(blank=True, max_length=500, null=True)),
                ('consulta_fecha', models.DateField()),
                ('finalizada', models.BooleanField()),
            ],
            options={
                'db_table': 'consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id_inspeccion', models.AutoField(primary_key=True, serialize=False)),
                ('observacion_inspeccion', models.CharField(blank=True, max_length=150, null=True)),
                ('esquema_inspeccion', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'inspeccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_suministro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_suministro', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.TextField()),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('telefono', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.TextField()),
                ('fecha_pago', models.DateField()),
                ('concepto_pago', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
    ]
